apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: image-pull-secret
  namespace: hello-t-mobile
stringData:
  .dockerconfigjson: '{"auths": {"artifactory.sikademo.com": {"username": "admin", "password": "password"}}}'
